version: '3.3'
services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acme
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    healthcheck:
      test: ["CMD", "test", "-e", "/var/run/mysqld/mysqld.sock"]
      interval: 5s
      retries: 5
    ports:
      - "3306:3306"
  app:
    build:
      context: ./
      dockerfile: invillia.docker
    image: invillia/invillia
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  db_data: {}